"""esquema inicial

Revision ID: f7459556b934
Revises: 
Create Date: 2026-10-04 18:29:35.878595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7459556b934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TBL_PRODUTO',
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('Nome_produto', sa.String(length=100), nullable=False),
    sa.Column('Quantidade_produto', sa.Integer(), nullable=False),
    sa.Column('Minimo_produto', sa.Integer(), nullable=False),
    sa.CheckConstraint('Minimo_produto >= 0', name='ck_produto_minimo'),
    sa.CheckConstraint('Quantidade_produto >= 0', name='ck_produto_quantidade'),
    sa.PrimaryKeyConstraint('id_produto')
    )
    op.create_table('TBL_USUARIO',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('Nome_usuario', sa.String(length=100), nullable=False),
    sa.Column('Email_usuario', sa.String(length=100), nullable=False),
    sa.Column('Senha_usuario', sa.String(length=255), nullable=False),
    sa.Column('Perfil_usuario', sa.String(length=45), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.CheckConstraint("Perfil_usuario IN ('admin', 'comum')", name='ck_usuario_perfil'),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('Email_usuario')
    )
    op.create_table('TBL_MOVIMENTACAO',
    sa.Column('id_movimentacao', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('TBL_USUARIO_id', sa.Integer(), nullable=False),
    sa.Column('TBL_PRODUTO_id_produto', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo_movimentacao IN ('entrada', 'saida')", name='ck_mov_tipo'),
    sa.CheckConstraint('quantidade > 0', name='ck_mov_quantidade'),
    sa.ForeignKeyConstraint(['TBL_PRODUTO_id_produto'], ['TBL_PRODUTO.id_produto'], ),
    sa.ForeignKeyConstraint(['TBL_USUARIO_id'], ['TBL_USUARIO.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_movimentacao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TBL_MOVIMENTACAO')
    op.drop_table('TBL_USUARIO')
    op.drop_table('TBL_PRODUTO')
    # ### end Alembic commands ###
